# Generated by Django 3.2.16 on 2023-05-06 05:10

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0005_delete_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='bo_title', max_length=255)),
                ('content', models.TextField(blank=True, db_column='bo_content', null=True)),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
                ('parent_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_board_set', to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'board',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
    ]
