# Generated by Django 3.2.16 on 2022-11-16 07:17

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20221116_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ch_name', default='', max_length=255, null=True)),
                ('type', models.CharField(db_column='ch_type', default='messenger', max_length=100)),
                ('description', models.TextField(blank=True, db_column='ch_description', default='', null=True)),
                ('is_archive', models.BooleanField(db_column='ch_is_archive', default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('owner', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='ChannelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'channel_content',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
                ('comment_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_message_set', to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'message',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MessengerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notification', models.BooleanField(db_column='ms_notification', default=True)),
                ('mobile_notification', models.BooleanField(db_column='ms_mobile_notification', default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channel')),
                ('last_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'messenger_member',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
                ('parent_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_board_set', to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'board',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
    ]
