# Generated by Django 3.2.16 on 2022-11-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='cc_created', null=True),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_column='cc_updated', null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, db_column='bo_content', null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='parent_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_board_set', to='messenger.channelcontent'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(db_column='bo_title', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, db_column='ch_description', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(db_column='ch_name', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='comment_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_message_set', to='messenger.channelcontent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, db_column='ms_content', null=True),
        ),
        migrations.AlterField(
            model_name='messengermember',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.message'),
        ),
    ]
