# Generated by Django 3.2.16 on 2023-02-11 11:09

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20221202_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.TextField(db_column='li_url')),
                ('image', models.TextField(db_column='li_image')),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
                ('parent_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_link_set', to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'link',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
    ]
