# Generated by Django 3.2.16 on 2023-05-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
