# Generated by Django 3.2.16 on 2023-05-19 07:50

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_delete_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, db_column='ms_file', null=True, upload_to=messenger.models.MessageFileMixin.upload_to),
        ),
    ]
