# Generated by Django 3.2.16 on 2023-05-22 05:18

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='parent_content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, db_column='fi_file', null=True, upload_to=messenger.models.upload_to)),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'file',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
    ]
