# Generated by Django 3.2.16 on 2023-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20230522_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcontent',
            name='timer',
            field=models.DateTimeField(blank=True, db_column='cc_timer', null=True),
        ),
    ]
