# Generated by Django 3.2.16 on 2023-06-13 05:33

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Channel = apps.get_model("messenger", "Channel")
    MessengerMember = apps.get_model("messenger", "MessengerMember")
    subowner = models.Subquery(MessengerMember.objects.filter(channel_id=models.OuterRef('id')).exclude(user_id=models.F('channel__owner_id')).values_list('user_id', flat=True)[:1])
    channel_queryset = Channel.objects.all().annotate(subowner_result=subowner)
    channels = [setattr(channel, 'subowner_id', channel.subowner_result) or channel for channel in channel_queryset]
    Channel.objects.bulk_update(channels, ['subowner'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221116_0501'),
        ('messenger', '0008_channelcontent_timer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='channel',
                    name='subowner',
                    field=models.ForeignKey(db_column='subuser_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subchannel_set', to='accounts.user'),
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name='channel',
                    name='subowner_id',
                    field=models.IntegerField(db_column='subuser_id', null=True),
                ),
            ]
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
