# Generated by Django 3.2.16 on 2023-06-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221116_0501'),
        ('messenger', '0009_channel_subowner'),
    ]

    operations = [
         migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='channel',
                    name='owner',
                    field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
                ),
                migrations.AlterField(
                    model_name='channel',
                    name='name',
                    field=models.CharField(blank=True, db_column='ch_name', default='', max_length=255),
                ),
            ],
            database_operations=[
                migrations.AlterField(
                    model_name='channel',
                    name='owner_id',
                    field=models.IntegerField(db_column='user_id', null=True),
                ),
            ]
        )
        
        
    ]
