# Generated by Django 3.2.16 on 2023-10-01 08:44

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


def forwards_func(apps, schema_editor):
    Attatchment = apps.get_model("messenger", "Attatchment")
    File = apps.get_model("messenger", "File")
    Link = apps.get_model("messenger", "Link")
    attatchments = []
    for f in File.objects.all():
        attatchments.append(Attatchment(
            channel_content=f.channel_content,
            type='file',
            file=f.file
        ))
        

    for l in Link.objects.all():
        attatchments.append(Attatchment(
            channel_content=l.channel_content,
            type='link',
            title=l.title,
            description=l.description,
            url=l.url,
            image_url=l.image
        ))
    Attatchment.objects.bulk_create(attatchments)


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_channelcontent_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='at_type', max_length=100)),
                ('file', models.FileField(blank=True, db_column='at_file', null=True, upload_to=messenger.models.upload_to)),
                ('title', models.CharField(db_column='at_title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='at_description', null=True)),
                ('url', models.TextField(blank=True, db_column='at_url', null=True)),
                ('image_url', models.TextField(blank=True, db_column='at_image', null=True)),
                ('channel_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channelcontent')),
            ],
            options={
                'db_table': 'attatchment',
            },
            bases=(messenger.models.ContentMixin, models.Model),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
