# Generated by Django 3.2.16 on 2023-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_auto_20231001_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='preview_content',
            field=models.CharField(blank=True, db_column='ms_preview_only', max_length=128, null=True),
        ),
    ]
