# Generated by Django 3.2.16 on 2023-10-01 15:29

from django.db import migrations
import easy_thumbnails.fields
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_message_preview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attatchment',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerField(blank=True, db_column='at_file', null=True, upload_to=messenger.models.upload_to),
        ),
    ]
