# Generated by Django 3.2.16 on 2023-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_alter_attatchment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='use_viewer',
            field=models.BooleanField(db_column='ch_use_viewer', default=False),
        ),
    ]
