# Generated by Django 3.2.16 on 2023-10-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_channel_use_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='use_editor',
            field=models.BooleanField(db_column='ms_use_editor', default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='preview_content',
            field=models.CharField(blank=True, db_column='ms_preview_content', max_length=128, null=True),
        ),
    ]
