# Generated by Django 3.2.16 on 2023-10-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0016_auto_20231012_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='use_editor',
        ),
    ]
